# Generated by Django 5.2.4 on 2025-10-19 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tournament Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('city', models.CharField(help_text='City where the event takes place', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Boys and Girls', 'Boys and Girls')], default='Boys', max_length=20)),
                ('level', models.CharField(default='Open', help_text='e.g. Under 14, Under 20', max_length=50)),
                ('duration_type', models.CharField(choices=[('League', 'League'), ('Tournament', 'Tournament')], max_length=10)),
                ('payment', models.CharField(default='Free', help_text='Enter amount in NRs or type "Free"', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_events', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
