# Generated by Django 5.2.4 on 2025-08-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tournament Name')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Boys and Girls', 'Boys and Girls')], default='Boys', max_length=20)),
                ('level', models.CharField(default='Open', help_text='e.g. Under 14, Under 20', max_length=50)),
                ('duration_type', models.CharField(choices=[('League', 'League'), ('Tournament', 'Tournament')], max_length=10)),
                ('payment', models.CharField(default='Free', help_text='Enter amount in NRs or type "Free"', max_length=20)),
            ],
        ),
    ]
