# Generated by Django 5.2.4 on 2025-08-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gender',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Boys and Girls', 'Boys and Girls')], default='Boys', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.CharField(default='Open', help_text='e.g. Under 14, Under 20', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='payment',
            field=models.CharField(default='Free', help_text='Enter amount in NRs or type "Free"', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tournament Name'),
        ),
    ]
