# Generated by Django 5.2.4 on 2025-10-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, help_text='Event logo image', null=True, upload_to='event_logos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_receipt',
            field=models.FileField(blank=True, help_text='Upload venue rental receipt for confirmation', null=True, upload_to='venue_receipts/'),
        ),
    ]
