# Generated by Django 5.2.4 on 2025-11-04 15:37

import django.core.validators
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_teams',
            field=models.IntegerField(default=16, help_text='Maximum number of teams that can enroll (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, help_text='Event logo (JPG, PNG, GIF, BMP, WEBP, SVG)', null=True, upload_to='event_logos/', validators=[events.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_receipt',
            field=models.FileField(blank=True, help_text='Venue rental receipt (PDF only)', null=True, upload_to='venue_receipts/', validators=[events.models.validate_pdf_extension]),
        ),
    ]
