# Generated by Django 5.2.4 on 2025-11-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_logo_event_venue_receipt'),
        ('events', '0003_event_max_teams_alter_event_logo_and_more'),
    ]

    operations = [
    ]
