# Generated by Django 5.2.4 on 2025-08-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Kathmandu', help_text='City where the event takes place', max_length=50),
            preserve_default=False,
        ),
    ]
