# Generated by Django 5.2.4 on 2025-08-11 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_event_gender_event_level_event_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('gender', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Boys and Girls', 'Boys and Girls')], default='Boys', max_length=20)),
                ('coach_name', models.CharField(max_length=100, verbose_name='Coach Name')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='enroll.enroll')),
            ],
        ),
    ]
