# Generated by Django 5.2.4 on 2025-08-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
        ('events', '0002_event_gender_event_level_event_payment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enroll',
            new_name='TeamEnroll',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='enroll',
            new_name='team',
        ),
    ]
