# Generated by Django 5.2.4 on 2025-08-20 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_event'),
        ('enroll', '0001_initial'),
        ('events', '0002_event_created_at_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamenroll',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='accounts.team'),
        ),
        migrations.AlterUniqueTogether(
            name='teamenroll',
            unique_together={('team_name', 'event')},
        ),
    ]
