# Generated by Django 5.2.4 on 2025-11-01 17:02
#0003_payment.py
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_player_options_teamenroll_coach_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('khalti_txn_id', models.CharField(blank=True, help_text='Khalti transaction ID', max_length=100, null=True)),
                ('reference_id', models.UUIDField(default=uuid.uuid4, help_text='Our unique reference', unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='khalti_payment', to='enroll.teamenroll')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
