# Generated by Django 5.2.4 on 2025-08-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_teamenroll_team_alter_teamenroll_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='grade',
        ),
    ]
