# Generated by Django 5.2.4 on 2025-08-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_rename_enroll_teamenroll_rename_enroll_player_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='teamenroll',
        ),
    ]
