# Generated by Django 5.2.4 on 2025-11-05 09:23
#004_payment_pidx_player_dob_player_id_proof_and_more.py
import django.db.models.deletion
import enroll.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pidx',
            field=models.CharField(blank=True, help_text='Khalti pidx (payment index) returned on initiate', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dob',
            field=models.DateField(blank=True, help_text="Player's date of birth from ID document", null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='player',
            name='id_proof',
            field=models.FileField(blank=True, help_text='ID document - citizenship, passport, student ID (PDF, max 10MB)', null=True, upload_to='player_documents/%Y/%m/%d/', validators=[enroll.models.validate_pdf_file]),
        ),
        migrations.AddField(
            model_name='player',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Has admin/organizer verified this player?'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_photo',
            field=models.ImageField(blank=True, help_text='Player photo (JPG or PNG, max 5MB)', null=True, upload_to='player_photos/%Y/%m/%d/', validators=[enroll.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='player',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Why was verification rejected?', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='unverified', help_text='Player verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When was player verified?', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin or organizer who verified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='khalti_txn_id',
            field=models.CharField(blank=True, help_text='Khalti transaction ID (from verification)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(help_text="Player's age at registration"),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_verified'], name='enroll_play_is_veri_ebeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['verification_status'], name='enroll_play_verific_3aa19e_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['teamenroll'], name='enroll_play_teamenr_5b8e4a_idx'),
        ),
    ]
