# Generated by Django 5.2.4 on 2025-08-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_remove_player_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jersey_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jersey Number'),
        ),
        migrations.AddField(
            model_name='teamenroll',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='Team Logo'),
        ),
    ]
