# Generated by Django 5.2.4 on 2025-11-07 15:44

import enroll.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_payment_pidx_player_dob_player_id_proof_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='player',
            name='enroll_play_is_veri_ebeb4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='enroll_play_verific_3aa19e_idx',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='enroll_play_teamenr_5b8e4a_idx',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='player',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='player',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='player',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='player',
            name='jersey_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='khalti_txn_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pidx',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='dob',
            field=models.DateField(default='2005-01-01', verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='id_proof',
            field=models.FileField(default='', upload_to='player_documents/%Y/%m/%d/', validators=[enroll.models.validate_pdf_file]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='player_photo',
            field=models.ImageField(default='', upload_to='player_photos/%Y/%m/%d/', validators=[enroll.models.validate_image_file]),
            preserve_default=False,
        ),
    ]
