# Generated by Django 5.2.4 on 2025-08-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_player_jersey_no_teamenroll_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamenroll',
            name='photo',
        ),
    ]
