# Generated by Django 5.2.4 on 2025-11-07 15:55

import enroll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_remove_player_enroll_play_is_veri_ebeb4b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='player_documents/%Y/%m/%d/', validators=[enroll.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos/%Y/%m/%d/', validators=[enroll.models.validate_image_file]),
        ),
    ]
