# Generated by Django 5.2.4 on 2025-08-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_remove_teamenroll_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='jersey_no',
        ),
    ]
