# Generated by Django 5.2.4 on 2025-12-29 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_alter_player_dob_alter_player_id_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='khalti_payment', to='enroll.teamenroll'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pidx',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
